# Generated by Django 4.2.11 on 2024-05-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
